#pragma once
#include "Main.h"
#include "Singleton.h"
//typedef void (*IJL_VOID)(void);
typedef void (*DBG_VOID)(void);

class CDBGHook
{
public:
	CDBGHook() { hDBG = NULL; }
	~CDBGHook();
	bool Hook();
	void SetSSQuality(int quality);
	int GetSSQuality(void);
private:
//	HMODULE hIJL;
	HMODULE hDBG;
};
typedef Singleton<CDBGHook> SngDBGHook;

// Mss32.dlx exports

extern "C"
{
__declspec(dllexport) void __stdcall AIL_get_preference(BYTE);
__declspec(dllexport) void __stdcall AIL_lock();
__declspec(dllexport) void __stdcall AIL_unlock();
__declspec(dllexport) void __stdcall AIL_lock_mutex();
__declspec(dllexport) void __stdcall AIL_unlock_mutex();
__declspec(dllexport) void __stdcall AIL_get_timer_highest_delay();
//__declspec(dllexport) void __stdcall DllMain();
__declspec(dllexport) void __stdcall RIB_load_static_provider_library(BYTE, BYTE);
__declspec(dllexport) void RIB_alloc_provider_handle();
__declspec(dllexport) void RIB_free_provider_handle();
__declspec(dllexport) void RIB_load_provider_library();
__declspec(dllexport) void RIB_free_provider_library();
__declspec(dllexport) void RIB_register_interface();
__declspec(dllexport) void RIB_request_interface();
__declspec(dllexport) void RIB_request_interface_entry();
__declspec(dllexport) void RIB_unregister_interface();
__declspec(dllexport) void RIB_enumerate_interface();
__declspec(dllexport) void __stdcall RIB_enumerate_providers(BYTE, BYTE, BYTE);
__declspec(dllexport) void RIB_type_string();
__declspec(dllexport) void RIB_find_file_provider();
__declspec(dllexport) void __stdcall RIB_find_files_provider(BYTE,BYTE,BYTE,BYTE,BYTE);
__declspec(dllexport) void __stdcall RIB_find_file_dec_provider(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall RIB_find_provider(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall RIB_load_application_providers(BYTE);
__declspec(dllexport) void __stdcall RIB_set_provider_user_data(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall RIB_provider_user_data(BYTE, BYTE);
__declspec(dllexport) void __stdcall RIB_set_provider_system_data(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall RIB_provider_system_data(BYTE, BYTE);
__declspec(dllexport) void RIB_error();
__declspec(dllexport) void __stdcall AIL_set_file_async_callbacks(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_file_callbacks(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_list_DLS(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_list_MIDI(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void stream_background();
__declspec(dllexport) void __stdcall AIL_ms_count();
__declspec(dllexport) void __stdcall AIL_us_count();
__declspec(dllexport) void __stdcall AIL_MMX_available();
__declspec(dllexport) void AIL_debug_printf();
__declspec(dllexport) void __stdcall AIL_startup();
__declspec(dllexport) void __stdcall AIL_shutdown();
__declspec(dllexport) void __stdcall AIL_HWND();
__declspec(dllexport) void __stdcall AIL_mem_alloc_lock(BYTE);
__declspec(dllexport) void __stdcall AIL_mem_free_lock(BYTE);
__declspec(dllexport) void __stdcall AIL_set_preference(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_last_error();
__declspec(dllexport) void __stdcall AIL_set_error(BYTE);
__declspec(dllexport) void __stdcall AIL_delay(BYTE);
__declspec(dllexport) void __stdcall AIL_background();
__declspec(dllexport) void __stdcall AIL_register_timer(BYTE);
__declspec(dllexport) void __stdcall AIL_set_timer_user(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_timer_period(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_timer_frequency(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_timer_divisor(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_start_timer(BYTE);
__declspec(dllexport) void __stdcall AIL_start_all_timers();
__declspec(dllexport) void __stdcall AIL_stop_timer(BYTE);
__declspec(dllexport) void __stdcall AIL_stop_all_timers();
__declspec(dllexport) void __stdcall AIL_release_timer_handle(BYTE);
__declspec(dllexport) void __stdcall AIL_release_all_timers();
__declspec(dllexport) void __stdcall AIL_open_digital_driver(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_close_digital_driver(BYTE);
__declspec(dllexport) void __stdcall AIL_waveOutOpen(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_waveOutClose(BYTE);
__declspec(dllexport) void __stdcall AIL_digital_handle_release(BYTE);
__declspec(dllexport) void __stdcall AIL_digital_handle_reacquire(BYTE);
__declspec(dllexport) void __stdcall AIL_open_input(BYTE);
__declspec(dllexport) void __stdcall AIL_close_input(BYTE);
__declspec(dllexport) void __stdcall AIL_get_input_info(BYTE);
__declspec(dllexport) void __stdcall AIL_set_input_state(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_digital_CPU_percent(BYTE);
__declspec(dllexport) void __stdcall AIL_digital_latency(BYTE);
__declspec(dllexport) void __stdcall AIL_allocate_sample_handle(BYTE);
__declspec(dllexport) void __stdcall AIL_allocate_file_sample(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_release_sample_handle(BYTE);
__declspec(dllexport) void __stdcall AIL_init_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_file(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_named_sample_file(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_processor(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_processor(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_DLS_processor(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_digital_driver_processor(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_address(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_type(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_adpcm_block_size(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_start_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_stop_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_resume_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_end_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_playback_rate(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_volume_pan(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_volume_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_low_pass_cut_off(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_loop_count(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_loop_block(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_status(BYTE);
__declspec(dllexport) void __stdcall AIL_sample_playback_rate(BYTE);
__declspec(dllexport) void __stdcall AIL_sample_volume_pan(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_volume_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_low_pass_cut_off(BYTE);
__declspec(dllexport) void __stdcall AIL_sample_loop_count(BYTE);
__declspec(dllexport) void __stdcall AIL_set_digital_master_volume_level(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_digital_master_volume_level(BYTE);
__declspec(dllexport) void __stdcall AIL_set_digital_master_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_digital_master_room_type(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_digital_master_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_digital_master_reverb(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_digital_master_reverb(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_minimum_sample_buffer_size(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_buffer_ready(BYTE);
__declspec(dllexport) void __stdcall AIL_load_sample_buffer(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_buffer_info(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_granularity(BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_position(BYTE);
__declspec(dllexport) void __stdcall AIL_register_SOB_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_EOB_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_EOS_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_EOF_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_user_data(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_user_data(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_active_sample_count(BYTE);
__declspec(dllexport) void __stdcall AIL_digital_configuration(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_get_DirectSound_info(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_DirectSound_HWND(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_open_XMIDI_driver(BYTE);
__declspec(dllexport) void __stdcall AIL_close_XMIDI_driver(BYTE);
__declspec(dllexport) void __stdcall AIL_midiOutOpen(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_midiOutClose(BYTE);
__declspec(dllexport) void __stdcall AIL_MIDI_handle_release(BYTE);
__declspec(dllexport) void __stdcall AIL_MIDI_handle_reacquire(BYTE);
__declspec(dllexport) void __stdcall AIL_allocate_sequence_handle(BYTE);
__declspec(dllexport) void __stdcall AIL_release_sequence_handle(BYTE);
__declspec(dllexport) void __stdcall AIL_init_sequence(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_start_sequence(BYTE);
__declspec(dllexport) void __stdcall AIL_stop_sequence(BYTE);
__declspec(dllexport) void __stdcall AIL_resume_sequence(BYTE);
__declspec(dllexport) void __stdcall AIL_end_sequence(BYTE);
__declspec(dllexport) void __stdcall AIL_set_sequence_tempo(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sequence_volume(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sequence_loop_count(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sequence_status(BYTE);
__declspec(dllexport) void __stdcall AIL_sequence_tempo(BYTE);
__declspec(dllexport) void __stdcall AIL_sequence_volume(BYTE);
__declspec(dllexport) void __stdcall AIL_sequence_loop_count(BYTE);
__declspec(dllexport) void __stdcall AIL_set_XMIDI_master_volume(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_XMIDI_master_volume(BYTE);
__declspec(dllexport) void __stdcall AIL_active_sequence_count(BYTE);
__declspec(dllexport) void __stdcall AIL_controller_value(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_channel_notes(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sequence_position(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_branch_index(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_prefix_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_trigger_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_sequence_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_beat_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_event_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_timbre_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sequence_user_data(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sequence_user_data(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_ICA_array(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_lock_channel(BYTE);
__declspec(dllexport) void __stdcall AIL_release_channel(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_map_sequence_channel(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_true_sequence_channel(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_send_channel_voice_message(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_send_sysex_message(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_create_wave_synthesizer(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_destroy_wave_synthesizer(BYTE);
__declspec(dllexport) void __stdcall AIL_file_error();
__declspec(dllexport) void __stdcall AIL_file_size(BYTE);
__declspec(dllexport) void __stdcall AIL_file_read(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_file_write(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_WAV_file_write(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_serve();
__declspec(dllexport) void __stdcall AIL_redbook_open(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_open_drive(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_close(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_eject(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_retract(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_status(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_tracks(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_track(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_track_info(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_id(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_position(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_play(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_stop(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_pause(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_resume(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_volume_level(BYTE);
__declspec(dllexport) void __stdcall AIL_redbook_set_volume_level(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_startup(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_shutdown();
__declspec(dllexport) void __stdcall AIL_quick_handles(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_load(BYTE);
__declspec(dllexport) void __stdcall AIL_quick_load_mem(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_copy(BYTE);
__declspec(dllexport) void __stdcall AIL_quick_unload(BYTE);
__declspec(dllexport) void __stdcall AIL_quick_play(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_halt(BYTE);
__declspec(dllexport) void __stdcall AIL_quick_status(BYTE);
__declspec(dllexport) void __stdcall AIL_quick_load_and_play(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_set_speed(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_set_volume(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_set_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_set_low_pass_cut_off(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_open_stream(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_close_stream(BYTE);
__declspec(dllexport) void __stdcall AIL_service_stream(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_start_stream(BYTE);
__declspec(dllexport) void __stdcall AIL_pause_stream(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_volume_pan(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_volume_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_low_pass_cut_off(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_volume_pan(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_volume_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_low_pass_cut_off(BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_playback_rate(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_playback_rate(BYTE);
__declspec(dllexport) void __stdcall AIL_stream_loop_count(BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_loop_block(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_loop_count(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_status(BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_position(BYTE);
__declspec(dllexport) void __stdcall AIL_stream_info(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_stream_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_auto_service_stream(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_user_data(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_user_data(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_open(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_close(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_load_file(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_load_memory(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_unload(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_compact(BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_set_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_get_reverb_levels(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_DLS_get_info(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sequence_ms_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sequence_ms_position(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_sample_ms_position(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_sample_ms_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_stream_ms_position(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_stream_ms_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_set_ms_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_quick_ms_position(BYTE);
__declspec(dllexport) void __stdcall AIL_quick_ms_length(BYTE);
__declspec(dllexport) void __stdcall AIL_quick_type(BYTE);
__declspec(dllexport) void __stdcall AIL_MIDI_to_XMI(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_compress_ADPCM(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_decompress_ADPCM(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_WAV_info(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_file_type(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_find_DLS(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_extract_DLS(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_primary_digital_driver(BYTE);
__declspec(dllexport) void __stdcall AIL_enumerate_filters(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_open_filter(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_close_filter(BYTE);
__declspec(dllexport) void __stdcall AIL_enumerate_filter_attributes(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_enumerate_filter_sample_attribute(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_filter_attribute(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_filter_sample_attribute(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_filter_stream_attribute(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_filter_DLS_attribute(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_filter_preference(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_filter_sample_preference(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_filter_stream_preference(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_filter_DLS_preference(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_enumerate_3D_providers(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_open_3D_provider(BYTE);
__declspec(dllexport) void __stdcall AIL_close_3D_provider(BYTE);
__declspec(dllexport) void __stdcall AIL_enumerate_3D_provider_attributes(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_enumerate_3D_sample_attributes(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_provider_attribute(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_attribute(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_provider_preference(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_preference(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_allocate_3D_sample_handle(BYTE);
__declspec(dllexport) void __stdcall AIL_release_3D_sample_handle(BYTE);
__declspec(dllexport) void __stdcall AIL_start_3D_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_stop_3D_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_resume_3D_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_end_3D_sample(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_info(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_file(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_volume(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_playback_rate(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_offset(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_loop_count(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_loop_block(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_obstruction(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_exclusion(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_occlusion(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_cone(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_effects_level(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_register_3D_EOS_callback(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_obstruction(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_exclusion(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_occlusion(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_cone(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_effects_level(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_status(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_volume(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_playback_rate(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_offset(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_length(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_loop_count(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_sample_distances(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_sample_distances(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_user_data(BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_user_data(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_active_3D_sample_count(BYTE);
__declspec(dllexport) void __stdcall AIL_3D_room_type(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_room_type(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_speaker_type(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_speaker_type(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_rolloff_factor(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_rolloff_factor(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_doppler_factor(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_doppler_factor(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_distance_factor(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_distance_factor(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_open_3D_listener(BYTE);
__declspec(dllexport) void __stdcall AIL_close_3D_listener(BYTE);
__declspec(dllexport) void __stdcall AIL_open_3D_object(BYTE);
__declspec(dllexport) void __stdcall AIL_close_3D_object(BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_position(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_velocity(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_velocity_vector(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_3D_orientation(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_position(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_velocity(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_3D_orientation(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_update_3D_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_auto_update_3D_position(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_size_processed_digital_audio(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_process_digital_audio(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_merge_DLS_with_XMI(BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_compress_DLS(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_filter_DLS_with_XMI(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_compress_ASI(BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_decompress_ASI(BYTE, BYTE, BYTE, BYTE, BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_request_EOB_ASI_reset(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_set_redist_directory(BYTE);
__declspec(dllexport) void __stdcall MIX_RIB_MAIN(BYTE, BYTE);
__declspec(dllexport) void __stdcall AIL_mem_use_malloc(BYTE);
__declspec(dllexport) void __stdcall AIL_mem_use_free(BYTE);
__declspec(dllexport) void AIL_sprintf();
__declspec(dllexport) void DLSMSSOpen();
__declspec(dllexport) void DLSClose();
__declspec(dllexport) void DLSLoadFile();
__declspec(dllexport) void DLSLoadMemFile();
__declspec(dllexport) void DLSGetInfo();
__declspec(dllexport) void DLSCompactMemory();
__declspec(dllexport) void DLSUnloadAll();
__declspec(dllexport) void DLSUnloadFile();
__declspec(dllexport) void DLSSetAttribute();
__declspec(dllexport) void __stdcall DLSMSSGetCPU(BYTE);
}
/*
// IJL.dll exports
void ijlGetLibVersion();
void ijlInit();
void ijlFree();
void ijlRead();
void ijlWrite();
void ijlErrorStr();
*/
